apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acme-explorer-api
  name: acme-explorer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-explorer-api-pod
  template:
    metadata:
      labels:
        app: acme-explorer-api-pod
    spec:
      containers:
      - name: acme-explorer-api-container
        env:
        - name: NODE_ENV
          value: "development"
        - name: MONGO_DB_HOST
          value: "mongodb-service"
        - name: MONGO_DB_PORT
          value: "27017"
        - name: MONGO_DB_USER
          value: "user"
        - name: MONGO_DB_PASSWORD
          value: "S3cret"
        - name: MONGO_DB_NAME
          value: "acme_explorer"
        - name: API_PORT
          value: "8080"
        - name: "FIREBASE_PROJECT_ID"
          value: "acme-explorer-auth"
        - name: FIREBASE_CLIENT_EMAIL
          value: "***"
        - name: FIREBASE_ADMIN_PRIVATE_KEY
          value: "***"
        resources: {}
        image: fvaldivian/acme-explorer-pf:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always