apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-explorer-api
  name: acme-explorer-api-service
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 31607
    targetPort: 8080
  selector:
    app: acme-explorer-api-pod
  type: NodePort