version: '3'
services:
  api:
    image: "fvaldivian/acme-explorer-pf:latest"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_PORT=${API_PORT:-8080}
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    restart: on-failure
    depends_on:
      - mongodb
    volumes:
      - "logging:/usr/src/app/logs"
  mongodb:
    image: "mongo"
    command: --logpath /var/log/mongodb/db.log
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "datavol:/data/db"
      - "logging:/var/log/mongodb"
volumes:
  logging:
    external: true
  datavol:
  